# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-13 07:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='name')),
                ('sex', models.IntegerField(choices=[(1, 'man'), (2, 'woman'), (3, 'unknown')], verbose_name='sex')),
                ('profession', models.CharField(max_length=128, verbose_name='profession')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('qq', models.CharField(max_length=128, verbose_name='qq')),
                ('phone', models.CharField(max_length=128, verbose_name='phone')),
                ('status', models.IntegerField(choices=[(1, 'applied'), (2, 'passed'), (3, 'denied')], verbose_name='check status')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='created time')),
            ],
        ),
    ]
