# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-15 06:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='name')),
                ('work_time', models.CharField(max_length=128, verbose_name='work time')),
                ('work_location', models.CharField(max_length=128, verbose_name='work location')),
            ],
            options={
                'verbose_name': 'information of work',
                'verbose_name_plural': 'information of work',
            },
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
