# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-25 03:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0002_auto_20171115_0617'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=20)),
                ('enable', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterModelOptions(
            name='work',
            options={'verbose_name': '\u517c\u804c\u516c\u544a', 'verbose_name_plural': '\u517c\u804c\u516c\u544a'},
        ),
        migrations.AlterField(
            model_name='work',
            name='name',
            field=models.CharField(max_length=128, verbose_name='\u540d\u5b57'),
        ),
        migrations.AlterField(
            model_name='work',
            name='work_location',
            field=models.CharField(max_length=128, verbose_name='\u5de5\u4f5c\u5730\u70b9'),
        ),
        migrations.AlterField(
            model_name='work',
            name='work_time',
            field=models.CharField(max_length=128, verbose_name='\u5de5\u4f5c\u65f6\u95f4'),
        ),
    ]
